export const REJECT_REASON = {
  DUPLICATE_EMAIL: 'duplicate-email',
  INVALID_EMAIL: 'invalid-email',
  USER_MISSING: 'user-missing',
  ITEM_MISSING: 'item-missing',
  TEAM_MISSING: 'team-missing',
  MENTOR_ID_UNRESOLVED: 'mentor-id-unresolved',
  SOFT_DELETED: 'soft-deleted',
  ROLE_DELETED: 'role-deleted',
  POOL_ENTRY_INACTIVE: 'pool-entry-inactive',
  MEMBER_INACTIVE: 'member-inactive',
  MEMBER_DUPLICATE: 'member-duplicate',
  SUBMISSION_DUPLICATE: 'submission-duplicate',
} as const;

export type TRejectReason = (typeof REJECT_REASON)[keyof typeof REJECT_REASON];

export const ADJUSTMENT_RULE = {
  ACCOUNT_SKIPPED: 'account-skipped',
  USER_DISABLED: 'user-disabled',
  PROFILE_METADATA_INVALID: 'profile-metadata-invalid',
  PERMISSION_UNMAPPED: 'permission-unmapped',
  ROLE_FIXED: 'role-fixed',
  ROLE_CUSTOM: 'role-custom',
  USER_ROLE_CHANGED: 'user-role-changed',
  ROLE_GRANT_MANUAL: 'role-grant-manual',
  FILE_COPY_PLANNED: 'file-copy-planned',
  FILE_UNSUPPORTED: 'file-unsupported',
  GACHA_WEIGHT_CLAMPED: 'gacha-weight-clamped',
  GACHA_STOCK_CLAMPED: 'gacha-stock-clamped',
  GACHA_POOL_FOLDED: 'gacha-pool-folded',
  GACHA_POOL_PLACEHOLDER: 'gacha-pool-placeholder',
  GACHA_STOCK_ZEROED: 'gacha-stock-zeroed',
  GACHA_TEST_ITEM_RETIRED: 'gacha-test-item-retired',
  CREDIT_MERGED: 'credit-merged',
  CREDIT_CLAMPED: 'credit-clamped',
  CLAIM_METADATA_PRESENT: 'claim-metadata-present',
  CLAIM_VALUE_MAPPED: 'claim-value-mapped',
  EVENT_PRICE_ROUNDED: 'event-price-rounded',
  EVENT_PRICE_CLAMPED: 'event-price-clamped',
  ROADMAP_STATUS_DEFAULTED: 'roadmap-status-defaulted',
  QR_ACTIVE_DEMOTED: 'qr-active-demoted',
  QR_CREATOR_CLEARED: 'qr-creator-cleared',
  MENTOR_ID_GENERATED: 'mentor-id-generated',
  MENTOR_STATUS_UNKNOWN: 'mentor-status-unknown',
  SESSION_MENTOR_REPAIRED: 'session-mentor-repaired',
  SESSION_STATUS_UNKNOWN: 'session-status-unknown',
  SESSION_RATING_CLEARED: 'session-rating-cleared',
  HACKATHON_USER_CREATED: 'hackathon-user-created',
  HACKATHON_USER_MERGED: 'hackathon-user-merged',
  HACKATHON_LEADER_INSERTED: 'hackathon-leader-inserted',
  HACKATHON_LEADER_MISSING: 'hackathon-leader-missing',
  HACKATHON_VALUE_MAPPED: 'hackathon-value-mapped',
  HACKATHON_PENDING_REJECTED: 'hackathon-pending-rejected',
  HACKATHON_CREATOR_CLEARED: 'hackathon-creator-cleared',
} as const;

export type TAdjustmentRule =
  (typeof ADJUSTMENT_RULE)[keyof typeof ADJUSTMENT_RULE];
