const HACKATHON = '/hackathon';
const TEAMS = `${HACKATHON}/teams`;
const TEAM = `${TEAMS}/{id}`;
const TEAM_SCOPED = `${TEAMS}/{teamId}`;
const SUBMISSION = `${HACKATHON}/submissions/{id}`;
const ADMIN = `${HACKATHON}/admin`;

export const HACKATHON_ROUTE_PATH = {
  HACKATHON_PARTICIPANT_ME: `${HACKATHON}/participants/me`,
  HACKATHON_PARTICIPANT: `${HACKATHON}/participants/{userId}`,
  HACKATHON_TEAMS: TEAMS,
  HACKATHON_TEAMS_MINE: `${TEAMS}/mine`,
  HACKATHON_TEAM: TEAM,
  HACKATHON_TEAM_LEAVE: `${TEAM}/leave`,
  HACKATHON_TEAM_MEMBER: `${TEAM_SCOPED}/members/{userId}`,
  HACKATHON_TEAM_INVITATIONS: `${TEAM_SCOPED}/invitations`,
  HACKATHON_TEAM_JOIN_REQUESTS: `${TEAM_SCOPED}/join-requests`,
  HACKATHON_TEAM_MESSAGES: `${TEAM_SCOPED}/messages`,
  HACKATHON_TEAM_SUBMISSION: `${TEAM_SCOPED}/submission`,
  HACKATHON_INVITATIONS_MINE: `${HACKATHON}/invitations/mine`,
  HACKATHON_INVITATION_RESPOND: `${HACKATHON}/invitations/{id}/respond`,
  HACKATHON_JOIN_REQUESTS_MINE: `${HACKATHON}/join-requests/mine`,
  HACKATHON_JOIN_REQUEST_RESPOND: `${HACKATHON}/join-requests/{id}/respond`,
  HACKATHON_MESSAGE: `${HACKATHON}/messages/{id}`,
  HACKATHON_SUBMISSION: SUBMISSION,
  HACKATHON_SUBMISSION_SUBMIT: `${SUBMISSION}/submit`,
  HACKATHON_SUBMISSION_CONFIRM: `${SUBMISSION}/confirm`,
  HACKATHON_SUBMISSION_CANCEL: `${SUBMISSION}/cancel`,
  HACKATHON_UPLOADS: `${HACKATHON}/uploads`,
  HACKATHON_WINNERS: `${HACKATHON}/winners`,
  HACKATHON_CERTIFICATES_MINE: `${HACKATHON}/certificates/mine`,
  HACKATHON_CERTIFICATE: `${HACKATHON}/certificates/{id}`,
  HACKATHON_ADMIN_PARTICIPANTS: `${ADMIN}/participants`,
  HACKATHON_ADMIN_TEAMS: `${ADMIN}/teams`,
  HACKATHON_ADMIN_TEAM: `${ADMIN}/teams/{id}`,
  HACKATHON_ADMIN_SUBMISSIONS: `${ADMIN}/submissions`,
  HACKATHON_ADMIN_WINNERS: `${ADMIN}/winners`,
  HACKATHON_ADMIN_WINNER: `${ADMIN}/winners/{teamId}`,
} as const;
