const TESTIMONIAL_RESOURCE = '/testimonials';

export const TESTIMONIAL_ROUTE_PATH = {
  TESTIMONIALS: TESTIMONIAL_RESOURCE,
  TESTIMONIALS_MINE: `${TESTIMONIAL_RESOURCE}/mine`,
  TESTIMONIALS_MODERATION: `${TESTIMONIAL_RESOURCE}/moderation`,
  TESTIMONIAL: `${TESTIMONIAL_RESOURCE}/{id}`,
  TESTIMONIAL_STATUS: `${TESTIMONIAL_RESOURCE}/{id}/status`,
} as const;
