/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as PublicMaintenanceRouteImport } from './routes/_public/maintenance'
import { Route as PublicWinnersRouteImport } from './routes/_public/winners'
import { Route as AuthenticatedOnboardingUserRouteImport } from './routes/_authenticated/onboarding/user'
import { Route as AuthenticatedTeamsTeamIdRouteImport } from './routes/_authenticated/teams/$teamId'
import { Route as AuthenticatedTeamsBrowseRouteImport } from './routes/_authenticated/teams/browse'
import { Route as AuthenticatedTeamsCreateRouteImport } from './routes/_authenticated/teams/create'
import { Route as AuthenticatedUsersUserIdRouteImport } from './routes/_authenticated/users/$userId'
import { Route as PublicAuthCallbackRouteImport } from './routes/_public/auth/callback'
import { Route as PublicAuthForgotPasswordRouteImport } from './routes/_public/auth/forgot-password'
import { Route as PublicAuthLoginRouteImport } from './routes/_public/auth/login'
import { Route as PublicAuthResetPasswordRouteImport } from './routes/_public/auth/reset-password'
import { Route as PublicAuthSignupRouteImport } from './routes/_public/auth/signup'
import { Route as PublicCertificateCertIdRouteImport } from './routes/_public/certificate/$certId'
import { Route as AuthenticatedTeamsTeamIdChatRouteImport } from './routes/_authenticated/teams/$teamId/chat'
import { Route as AuthenticatedTeamsTeamIdEditRouteImport } from './routes/_authenticated/teams/$teamId/edit'
import { Route as AuthenticatedTeamsTeamIdMembersRouteImport } from './routes/_authenticated/teams/$teamId/members'
import { Route as AuthenticatedTeamsTeamIdSubmissionRouteImport } from './routes/_authenticated/teams/$teamId/submission'
import { Route as AuthenticatedTeamsTeamIdSubmitRouteImport } from './routes/_authenticated/teams/$teamId/submit'
import { Route as PublicCertificateWinnerCertIdRouteImport } from './routes/_public/certificate/winner/$certId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PublicMaintenanceRoute = PublicMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => PublicRoute,
} as any)
const PublicWinnersRoute = PublicWinnersRouteImport.update({
  id: '/winners',
  path: '/winners',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedOnboardingUserRoute =
  AuthenticatedOnboardingUserRouteImport.update({
    id: '/onboarding/user',
    path: '/onboarding/user',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTeamsTeamIdRoute =
  AuthenticatedTeamsTeamIdRouteImport.update({
    id: '/teams/$teamId',
    path: '/teams/$teamId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTeamsBrowseRoute =
  AuthenticatedTeamsBrowseRouteImport.update({
    id: '/teams/browse',
    path: '/teams/browse',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTeamsCreateRoute =
  AuthenticatedTeamsCreateRouteImport.update({
    id: '/teams/create',
    path: '/teams/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersUserIdRoute =
  AuthenticatedUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const PublicAuthCallbackRoute = PublicAuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAuthForgotPasswordRoute =
  PublicAuthForgotPasswordRouteImport.update({
    id: '/auth/forgot-password',
    path: '/auth/forgot-password',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicAuthLoginRoute = PublicAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAuthResetPasswordRoute = PublicAuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAuthSignupRoute = PublicAuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCertificateCertIdRoute = PublicCertificateCertIdRouteImport.update({
  id: '/certificate/$certId',
  path: '/certificate/$certId',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedTeamsTeamIdChatRoute =
  AuthenticatedTeamsTeamIdChatRouteImport.update({
    id: '/chat',
    path: '/chat',
    getParentRoute: () => AuthenticatedTeamsTeamIdRoute,
  } as any)
const AuthenticatedTeamsTeamIdEditRoute =
  AuthenticatedTeamsTeamIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedTeamsTeamIdRoute,
  } as any)
const AuthenticatedTeamsTeamIdMembersRoute =
  AuthenticatedTeamsTeamIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedTeamsTeamIdRoute,
  } as any)
const AuthenticatedTeamsTeamIdSubmissionRoute =
  AuthenticatedTeamsTeamIdSubmissionRouteImport.update({
    id: '/submission',
    path: '/submission',
    getParentRoute: () => AuthenticatedTeamsTeamIdRoute,
  } as any)
const AuthenticatedTeamsTeamIdSubmitRoute =
  AuthenticatedTeamsTeamIdSubmitRouteImport.update({
    id: '/submit',
    path: '/submit',
    getParentRoute: () => AuthenticatedTeamsTeamIdRoute,
  } as any)
const PublicCertificateWinnerCertIdRoute =
  PublicCertificateWinnerCertIdRouteImport.update({
    id: '/certificate/winner/$certId',
    path: '/certificate/winner/$certId',
    getParentRoute: () => PublicRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/maintenance': typeof PublicMaintenanceRoute
  '/winners': typeof PublicWinnersRoute
  '/onboarding/user': typeof AuthenticatedOnboardingUserRoute
  '/teams/$teamId': typeof AuthenticatedTeamsTeamIdRouteWithChildren
  '/teams/browse': typeof AuthenticatedTeamsBrowseRoute
  '/teams/create': typeof AuthenticatedTeamsCreateRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/auth/callback': typeof PublicAuthCallbackRoute
  '/auth/forgot-password': typeof PublicAuthForgotPasswordRoute
  '/auth/login': typeof PublicAuthLoginRoute
  '/auth/reset-password': typeof PublicAuthResetPasswordRoute
  '/auth/signup': typeof PublicAuthSignupRoute
  '/certificate/$certId': typeof PublicCertificateCertIdRoute
  '/teams/$teamId/chat': typeof AuthenticatedTeamsTeamIdChatRoute
  '/teams/$teamId/edit': typeof AuthenticatedTeamsTeamIdEditRoute
  '/teams/$teamId/members': typeof AuthenticatedTeamsTeamIdMembersRoute
  '/teams/$teamId/submission': typeof AuthenticatedTeamsTeamIdSubmissionRoute
  '/teams/$teamId/submit': typeof AuthenticatedTeamsTeamIdSubmitRoute
  '/certificate/winner/$certId': typeof PublicCertificateWinnerCertIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/maintenance': typeof PublicMaintenanceRoute
  '/winners': typeof PublicWinnersRoute
  '/onboarding/user': typeof AuthenticatedOnboardingUserRoute
  '/teams/$teamId': typeof AuthenticatedTeamsTeamIdRouteWithChildren
  '/teams/browse': typeof AuthenticatedTeamsBrowseRoute
  '/teams/create': typeof AuthenticatedTeamsCreateRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/auth/callback': typeof PublicAuthCallbackRoute
  '/auth/forgot-password': typeof PublicAuthForgotPasswordRoute
  '/auth/login': typeof PublicAuthLoginRoute
  '/auth/reset-password': typeof PublicAuthResetPasswordRoute
  '/auth/signup': typeof PublicAuthSignupRoute
  '/certificate/$certId': typeof PublicCertificateCertIdRoute
  '/teams/$teamId/chat': typeof AuthenticatedTeamsTeamIdChatRoute
  '/teams/$teamId/edit': typeof AuthenticatedTeamsTeamIdEditRoute
  '/teams/$teamId/members': typeof AuthenticatedTeamsTeamIdMembersRoute
  '/teams/$teamId/submission': typeof AuthenticatedTeamsTeamIdSubmissionRoute
  '/teams/$teamId/submit': typeof AuthenticatedTeamsTeamIdSubmitRoute
  '/certificate/winner/$certId': typeof PublicCertificateWinnerCertIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_public/maintenance': typeof PublicMaintenanceRoute
  '/_public/winners': typeof PublicWinnersRoute
  '/_authenticated/onboarding/user': typeof AuthenticatedOnboardingUserRoute
  '/_authenticated/teams/$teamId': typeof AuthenticatedTeamsTeamIdRouteWithChildren
  '/_authenticated/teams/browse': typeof AuthenticatedTeamsBrowseRoute
  '/_authenticated/teams/create': typeof AuthenticatedTeamsCreateRoute
  '/_authenticated/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/_public/auth/callback': typeof PublicAuthCallbackRoute
  '/_public/auth/forgot-password': typeof PublicAuthForgotPasswordRoute
  '/_public/auth/login': typeof PublicAuthLoginRoute
  '/_public/auth/reset-password': typeof PublicAuthResetPasswordRoute
  '/_public/auth/signup': typeof PublicAuthSignupRoute
  '/_public/certificate/$certId': typeof PublicCertificateCertIdRoute
  '/_authenticated/teams/$teamId/chat': typeof AuthenticatedTeamsTeamIdChatRoute
  '/_authenticated/teams/$teamId/edit': typeof AuthenticatedTeamsTeamIdEditRoute
  '/_authenticated/teams/$teamId/members': typeof AuthenticatedTeamsTeamIdMembersRoute
  '/_authenticated/teams/$teamId/submission': typeof AuthenticatedTeamsTeamIdSubmissionRoute
  '/_authenticated/teams/$teamId/submit': typeof AuthenticatedTeamsTeamIdSubmitRoute
  '/_public/certificate/winner/$certId': typeof PublicCertificateWinnerCertIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/maintenance'
    | '/winners'
    | '/onboarding/user'
    | '/teams/$teamId'
    | '/teams/browse'
    | '/teams/create'
    | '/users/$userId'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/certificate/$certId'
    | '/teams/$teamId/chat'
    | '/teams/$teamId/edit'
    | '/teams/$teamId/members'
    | '/teams/$teamId/submission'
    | '/teams/$teamId/submit'
    | '/certificate/winner/$certId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/maintenance'
    | '/winners'
    | '/onboarding/user'
    | '/teams/$teamId'
    | '/teams/browse'
    | '/teams/create'
    | '/users/$userId'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/certificate/$certId'
    | '/teams/$teamId/chat'
    | '/teams/$teamId/edit'
    | '/teams/$teamId/members'
    | '/teams/$teamId/submission'
    | '/teams/$teamId/submit'
    | '/certificate/winner/$certId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/dashboard'
    | '/_public/maintenance'
    | '/_public/winners'
    | '/_authenticated/onboarding/user'
    | '/_authenticated/teams/$teamId'
    | '/_authenticated/teams/browse'
    | '/_authenticated/teams/create'
    | '/_authenticated/users/$userId'
    | '/_public/auth/callback'
    | '/_public/auth/forgot-password'
    | '/_public/auth/login'
    | '/_public/auth/reset-password'
    | '/_public/auth/signup'
    | '/_public/certificate/$certId'
    | '/_authenticated/teams/$teamId/chat'
    | '/_authenticated/teams/$teamId/edit'
    | '/_authenticated/teams/$teamId/members'
    | '/_authenticated/teams/$teamId/submission'
    | '/_authenticated/teams/$teamId/submit'
    | '/_public/certificate/winner/$certId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_public/maintenance': {
      id: '/_public/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof PublicMaintenanceRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/winners': {
      id: '/_public/winners'
      path: '/winners'
      fullPath: '/winners'
      preLoaderRoute: typeof PublicWinnersRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/onboarding/user': {
      id: '/_authenticated/onboarding/user'
      path: '/onboarding/user'
      fullPath: '/onboarding/user'
      preLoaderRoute: typeof AuthenticatedOnboardingUserRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teams/$teamId': {
      id: '/_authenticated/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teams/browse': {
      id: '/_authenticated/teams/browse'
      path: '/teams/browse'
      fullPath: '/teams/browse'
      preLoaderRoute: typeof AuthenticatedTeamsBrowseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teams/create': {
      id: '/_authenticated/teams/create'
      path: '/teams/create'
      fullPath: '/teams/create'
      preLoaderRoute: typeof AuthenticatedTeamsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/$userId': {
      id: '/_authenticated/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AuthenticatedUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_public/auth/callback': {
      id: '/_public/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof PublicAuthCallbackRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth/forgot-password': {
      id: '/_public/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof PublicAuthForgotPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth/login': {
      id: '/_public/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof PublicAuthLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth/reset-password': {
      id: '/_public/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof PublicAuthResetPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth/signup': {
      id: '/_public/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof PublicAuthSignupRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/certificate/$certId': {
      id: '/_public/certificate/$certId'
      path: '/certificate/$certId'
      fullPath: '/certificate/$certId'
      preLoaderRoute: typeof PublicCertificateCertIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/teams/$teamId/chat': {
      id: '/_authenticated/teams/$teamId/chat'
      path: '/chat'
      fullPath: '/teams/$teamId/chat'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdChatRouteImport
      parentRoute: typeof AuthenticatedTeamsTeamIdRoute
    }
    '/_authenticated/teams/$teamId/edit': {
      id: '/_authenticated/teams/$teamId/edit'
      path: '/edit'
      fullPath: '/teams/$teamId/edit'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdEditRouteImport
      parentRoute: typeof AuthenticatedTeamsTeamIdRoute
    }
    '/_authenticated/teams/$teamId/members': {
      id: '/_authenticated/teams/$teamId/members'
      path: '/members'
      fullPath: '/teams/$teamId/members'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdMembersRouteImport
      parentRoute: typeof AuthenticatedTeamsTeamIdRoute
    }
    '/_authenticated/teams/$teamId/submission': {
      id: '/_authenticated/teams/$teamId/submission'
      path: '/submission'
      fullPath: '/teams/$teamId/submission'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdSubmissionRouteImport
      parentRoute: typeof AuthenticatedTeamsTeamIdRoute
    }
    '/_authenticated/teams/$teamId/submit': {
      id: '/_authenticated/teams/$teamId/submit'
      path: '/submit'
      fullPath: '/teams/$teamId/submit'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdSubmitRouteImport
      parentRoute: typeof AuthenticatedTeamsTeamIdRoute
    }
    '/_public/certificate/winner/$certId': {
      id: '/_public/certificate/winner/$certId'
      path: '/certificate/winner/$certId'
      fullPath: '/certificate/winner/$certId'
      preLoaderRoute: typeof PublicCertificateWinnerCertIdRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface AuthenticatedTeamsTeamIdRouteChildren {
  AuthenticatedTeamsTeamIdChatRoute: typeof AuthenticatedTeamsTeamIdChatRoute
  AuthenticatedTeamsTeamIdEditRoute: typeof AuthenticatedTeamsTeamIdEditRoute
  AuthenticatedTeamsTeamIdMembersRoute: typeof AuthenticatedTeamsTeamIdMembersRoute
  AuthenticatedTeamsTeamIdSubmissionRoute: typeof AuthenticatedTeamsTeamIdSubmissionRoute
  AuthenticatedTeamsTeamIdSubmitRoute: typeof AuthenticatedTeamsTeamIdSubmitRoute
}

const AuthenticatedTeamsTeamIdRouteChildren: AuthenticatedTeamsTeamIdRouteChildren =
  {
    AuthenticatedTeamsTeamIdChatRoute: AuthenticatedTeamsTeamIdChatRoute,
    AuthenticatedTeamsTeamIdEditRoute: AuthenticatedTeamsTeamIdEditRoute,
    AuthenticatedTeamsTeamIdMembersRoute: AuthenticatedTeamsTeamIdMembersRoute,
    AuthenticatedTeamsTeamIdSubmissionRoute:
      AuthenticatedTeamsTeamIdSubmissionRoute,
    AuthenticatedTeamsTeamIdSubmitRoute: AuthenticatedTeamsTeamIdSubmitRoute,
  }

const AuthenticatedTeamsTeamIdRouteWithChildren =
  AuthenticatedTeamsTeamIdRoute._addFileChildren(
    AuthenticatedTeamsTeamIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingUserRoute: typeof AuthenticatedOnboardingUserRoute
  AuthenticatedTeamsTeamIdRoute: typeof AuthenticatedTeamsTeamIdRouteWithChildren
  AuthenticatedTeamsBrowseRoute: typeof AuthenticatedTeamsBrowseRoute
  AuthenticatedTeamsCreateRoute: typeof AuthenticatedTeamsCreateRoute
  AuthenticatedUsersUserIdRoute: typeof AuthenticatedUsersUserIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingUserRoute: AuthenticatedOnboardingUserRoute,
  AuthenticatedTeamsTeamIdRoute: AuthenticatedTeamsTeamIdRouteWithChildren,
  AuthenticatedTeamsBrowseRoute: AuthenticatedTeamsBrowseRoute,
  AuthenticatedTeamsCreateRoute: AuthenticatedTeamsCreateRoute,
  AuthenticatedUsersUserIdRoute: AuthenticatedUsersUserIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicMaintenanceRoute: typeof PublicMaintenanceRoute
  PublicWinnersRoute: typeof PublicWinnersRoute
  PublicAuthCallbackRoute: typeof PublicAuthCallbackRoute
  PublicAuthForgotPasswordRoute: typeof PublicAuthForgotPasswordRoute
  PublicAuthLoginRoute: typeof PublicAuthLoginRoute
  PublicAuthResetPasswordRoute: typeof PublicAuthResetPasswordRoute
  PublicAuthSignupRoute: typeof PublicAuthSignupRoute
  PublicCertificateCertIdRoute: typeof PublicCertificateCertIdRoute
  PublicCertificateWinnerCertIdRoute: typeof PublicCertificateWinnerCertIdRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicMaintenanceRoute: PublicMaintenanceRoute,
  PublicWinnersRoute: PublicWinnersRoute,
  PublicAuthCallbackRoute: PublicAuthCallbackRoute,
  PublicAuthForgotPasswordRoute: PublicAuthForgotPasswordRoute,
  PublicAuthLoginRoute: PublicAuthLoginRoute,
  PublicAuthResetPasswordRoute: PublicAuthResetPasswordRoute,
  PublicAuthSignupRoute: PublicAuthSignupRoute,
  PublicCertificateCertIdRoute: PublicCertificateCertIdRoute,
  PublicCertificateWinnerCertIdRoute: PublicCertificateWinnerCertIdRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
