/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as SiteFeaturesRouteImport } from './routes/_site/features'
import { Route as SiteFaqRouteImport } from './routes/_site/faq'
import { Route as SiteDownloadRouteImport } from './routes/_site/download'
import { Route as SiteAboutRouteImport } from './routes/_site/about'
import { Route as SiteWikiIndexRouteImport } from './routes/_site/wiki/index'
import { Route as SiteWikiSlugRouteImport } from './routes/_site/wiki/$slug'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteFeaturesRoute = SiteFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => SiteRoute,
} as any)
const SiteFaqRoute = SiteFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => SiteRoute,
} as any)
const SiteDownloadRoute = SiteDownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SiteWikiIndexRoute = SiteWikiIndexRouteImport.update({
  id: '/wiki/',
  path: '/wiki/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteWikiSlugRoute = SiteWikiSlugRouteImport.update({
  id: '/wiki/$slug',
  path: '/wiki/$slug',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/about': typeof SiteAboutRoute
  '/download': typeof SiteDownloadRoute
  '/faq': typeof SiteFaqRoute
  '/features': typeof SiteFeaturesRoute
  '/wiki/$slug': typeof SiteWikiSlugRoute
  '/wiki/': typeof SiteWikiIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof SiteAboutRoute
  '/download': typeof SiteDownloadRoute
  '/faq': typeof SiteFaqRoute
  '/features': typeof SiteFeaturesRoute
  '/': typeof SiteIndexRoute
  '/wiki/$slug': typeof SiteWikiSlugRoute
  '/wiki': typeof SiteWikiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/_site/about': typeof SiteAboutRoute
  '/_site/download': typeof SiteDownloadRoute
  '/_site/faq': typeof SiteFaqRoute
  '/_site/features': typeof SiteFeaturesRoute
  '/_site/': typeof SiteIndexRoute
  '/_site/wiki/$slug': typeof SiteWikiSlugRoute
  '/_site/wiki/': typeof SiteWikiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/download'
    | '/faq'
    | '/features'
    | '/wiki/$slug'
    | '/wiki/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/download'
    | '/faq'
    | '/features'
    | '/'
    | '/wiki/$slug'
    | '/wiki'
  id:
    | '__root__'
    | '/_site'
    | '/_site/about'
    | '/_site/download'
    | '/_site/faq'
    | '/_site/features'
    | '/_site/'
    | '/_site/wiki/$slug'
    | '/_site/wiki/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/features': {
      id: '/_site/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof SiteFeaturesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/faq': {
      id: '/_site/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof SiteFaqRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/download': {
      id: '/_site/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof SiteDownloadRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/wiki/': {
      id: '/_site/wiki/'
      path: '/wiki'
      fullPath: '/wiki/'
      preLoaderRoute: typeof SiteWikiIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/wiki/$slug': {
      id: '/_site/wiki/$slug'
      path: '/wiki/$slug'
      fullPath: '/wiki/$slug'
      preLoaderRoute: typeof SiteWikiSlugRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteDownloadRoute: typeof SiteDownloadRoute
  SiteFaqRoute: typeof SiteFaqRoute
  SiteFeaturesRoute: typeof SiteFeaturesRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteWikiSlugRoute: typeof SiteWikiSlugRoute
  SiteWikiIndexRoute: typeof SiteWikiIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteDownloadRoute: SiteDownloadRoute,
  SiteFaqRoute: SiteFaqRoute,
  SiteFeaturesRoute: SiteFeaturesRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteWikiSlugRoute: SiteWikiSlugRoute,
  SiteWikiIndexRoute: SiteWikiIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
