/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated/accounts'
import { Route as AuthenticatedCmsEventsRouteImport } from './routes/_authenticated/cms-events'
import { Route as AuthenticatedCmsTestimonialsRouteImport } from './routes/_authenticated/cms-testimonials'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardDimentorinRouteImport } from './routes/_authenticated/dashboard-dimentorin'
import { Route as AuthenticatedFeedbackReviewDimentorinRouteImport } from './routes/_authenticated/feedback-review-dimentorin'
import { Route as AuthenticatedGachaRollRouteImport } from './routes/_authenticated/gacha-roll'
import { Route as AuthenticatedHackathonDashboardRouteImport } from './routes/_authenticated/hackathon-dashboard'
import { Route as AuthenticatedHackathonSubmissionsRouteImport } from './routes/_authenticated/hackathon-submissions'
import { Route as AuthenticatedHackathonTeamsRouteImport } from './routes/_authenticated/hackathon-teams'
import { Route as AuthenticatedHackathonUsersRouteImport } from './routes/_authenticated/hackathon-users'
import { Route as AuthenticatedPermissionsRouteImport } from './routes/_authenticated/permissions'
import { Route as AuthenticatedPrizesRouteImport } from './routes/_authenticated/prizes'
import { Route as AuthenticatedRoadmapDimentorinRouteImport } from './routes/_authenticated/roadmap-dimentorin'
import { Route as AuthenticatedRolesRouteImport } from './routes/_authenticated/roles'
import { Route as AuthenticatedSessionDimentorinRouteImport } from './routes/_authenticated/session-dimentorin'
import { Route as AuthenticatedSettingsDimentorinRouteImport } from './routes/_authenticated/settings-dimentorin'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedUsersDimentorinRouteImport } from './routes/_authenticated/users-dimentorin'
import { Route as AuthenticatedAccountsIdRouteImport } from './routes/_authenticated/accounts_/$id'
import { Route as AuthenticatedAccountsCreateRouteImport } from './routes/_authenticated/accounts_/create'
import { Route as AuthenticatedCmsEventsIdRouteImport } from './routes/_authenticated/cms-events_/$id'
import { Route as AuthenticatedCmsEventsCreateRouteImport } from './routes/_authenticated/cms-events_/create'
import { Route as AuthenticatedCmsTestimonialsIdRouteImport } from './routes/_authenticated/cms-testimonials_/$id'
import { Route as AuthenticatedCmsTestimonialsCreateRouteImport } from './routes/_authenticated/cms-testimonials_/create'
import { Route as AuthenticatedDashboardIdRouteImport } from './routes/_authenticated/dashboard_/$id'
import { Route as AuthenticatedDashboardCreateRouteImport } from './routes/_authenticated/dashboard_/create'
import { Route as AuthenticatedGachaRollIdRouteImport } from './routes/_authenticated/gacha-roll_/$id'
import { Route as AuthenticatedGachaRollCreateRouteImport } from './routes/_authenticated/gacha-roll_/create'
import { Route as AuthenticatedRoadmapDimentorinIdRouteImport } from './routes/_authenticated/roadmap-dimentorin_/$id'
import { Route as AuthenticatedRoadmapDimentorinCreateRouteImport } from './routes/_authenticated/roadmap-dimentorin_/create'
import { Route as AuthenticatedRolesIdRouteImport } from './routes/_authenticated/roles_/$id'
import { Route as AuthenticatedRolesCreateRouteImport } from './routes/_authenticated/roles_/create'
import { Route as AuthenticatedSessionDimentorinIdRouteImport } from './routes/_authenticated/session-dimentorin_/$id'
import { Route as AuthenticatedUsersDimentorinIdRouteImport } from './routes/_authenticated/users-dimentorin_/$id'
import { Route as PublicAuthLoginRouteImport } from './routes/_public/auth/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCmsEventsRoute = AuthenticatedCmsEventsRouteImport.update({
  id: '/cms-events',
  path: '/cms-events',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCmsTestimonialsRoute =
  AuthenticatedCmsTestimonialsRouteImport.update({
    id: '/cms-testimonials',
    path: '/cms-testimonials',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardDimentorinRoute =
  AuthenticatedDashboardDimentorinRouteImport.update({
    id: '/dashboard-dimentorin',
    path: '/dashboard-dimentorin',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFeedbackReviewDimentorinRoute =
  AuthenticatedFeedbackReviewDimentorinRouteImport.update({
    id: '/feedback-review-dimentorin',
    path: '/feedback-review-dimentorin',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGachaRollRoute = AuthenticatedGachaRollRouteImport.update({
  id: '/gacha-roll',
  path: '/gacha-roll',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHackathonDashboardRoute =
  AuthenticatedHackathonDashboardRouteImport.update({
    id: '/hackathon-dashboard',
    path: '/hackathon-dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHackathonSubmissionsRoute =
  AuthenticatedHackathonSubmissionsRouteImport.update({
    id: '/hackathon-submissions',
    path: '/hackathon-submissions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHackathonTeamsRoute =
  AuthenticatedHackathonTeamsRouteImport.update({
    id: '/hackathon-teams',
    path: '/hackathon-teams',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHackathonUsersRoute =
  AuthenticatedHackathonUsersRouteImport.update({
    id: '/hackathon-users',
    path: '/hackathon-users',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPermissionsRoute =
  AuthenticatedPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPrizesRoute = AuthenticatedPrizesRouteImport.update({
  id: '/prizes',
  path: '/prizes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRoadmapDimentorinRoute =
  AuthenticatedRoadmapDimentorinRouteImport.update({
    id: '/roadmap-dimentorin',
    path: '/roadmap-dimentorin',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRolesRoute = AuthenticatedRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSessionDimentorinRoute =
  AuthenticatedSessionDimentorinRouteImport.update({
    id: '/session-dimentorin',
    path: '/session-dimentorin',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsDimentorinRoute =
  AuthenticatedSettingsDimentorinRouteImport.update({
    id: '/settings-dimentorin',
    path: '/settings-dimentorin',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersDimentorinRoute =
  AuthenticatedUsersDimentorinRouteImport.update({
    id: '/users-dimentorin',
    path: '/users-dimentorin',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountsIdRoute = AuthenticatedAccountsIdRouteImport.update({
  id: '/accounts_/$id',
  path: '/accounts/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountsCreateRoute =
  AuthenticatedAccountsCreateRouteImport.update({
    id: '/accounts_/create',
    path: '/accounts/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCmsEventsIdRoute =
  AuthenticatedCmsEventsIdRouteImport.update({
    id: '/cms-events_/$id',
    path: '/cms-events/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCmsEventsCreateRoute =
  AuthenticatedCmsEventsCreateRouteImport.update({
    id: '/cms-events_/create',
    path: '/cms-events/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCmsTestimonialsIdRoute =
  AuthenticatedCmsTestimonialsIdRouteImport.update({
    id: '/cms-testimonials_/$id',
    path: '/cms-testimonials/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCmsTestimonialsCreateRoute =
  AuthenticatedCmsTestimonialsCreateRouteImport.update({
    id: '/cms-testimonials_/create',
    path: '/cms-testimonials/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardIdRoute =
  AuthenticatedDashboardIdRouteImport.update({
    id: '/dashboard_/$id',
    path: '/dashboard/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardCreateRoute =
  AuthenticatedDashboardCreateRouteImport.update({
    id: '/dashboard_/create',
    path: '/dashboard/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGachaRollIdRoute =
  AuthenticatedGachaRollIdRouteImport.update({
    id: '/gacha-roll_/$id',
    path: '/gacha-roll/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGachaRollCreateRoute =
  AuthenticatedGachaRollCreateRouteImport.update({
    id: '/gacha-roll_/create',
    path: '/gacha-roll/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRoadmapDimentorinIdRoute =
  AuthenticatedRoadmapDimentorinIdRouteImport.update({
    id: '/roadmap-dimentorin_/$id',
    path: '/roadmap-dimentorin/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRoadmapDimentorinCreateRoute =
  AuthenticatedRoadmapDimentorinCreateRouteImport.update({
    id: '/roadmap-dimentorin_/create',
    path: '/roadmap-dimentorin/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRolesIdRoute = AuthenticatedRolesIdRouteImport.update({
  id: '/roles_/$id',
  path: '/roles/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRolesCreateRoute =
  AuthenticatedRolesCreateRouteImport.update({
    id: '/roles_/create',
    path: '/roles/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSessionDimentorinIdRoute =
  AuthenticatedSessionDimentorinIdRouteImport.update({
    id: '/session-dimentorin_/$id',
    path: '/session-dimentorin/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersDimentorinIdRoute =
  AuthenticatedUsersDimentorinIdRouteImport.update({
    id: '/users-dimentorin_/$id',
    path: '/users-dimentorin/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const PublicAuthLoginRoute = PublicAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/cms-events': typeof AuthenticatedCmsEventsRoute
  '/cms-testimonials': typeof AuthenticatedCmsTestimonialsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dashboard-dimentorin': typeof AuthenticatedDashboardDimentorinRoute
  '/feedback-review-dimentorin': typeof AuthenticatedFeedbackReviewDimentorinRoute
  '/gacha-roll': typeof AuthenticatedGachaRollRoute
  '/hackathon-dashboard': typeof AuthenticatedHackathonDashboardRoute
  '/hackathon-submissions': typeof AuthenticatedHackathonSubmissionsRoute
  '/hackathon-teams': typeof AuthenticatedHackathonTeamsRoute
  '/hackathon-users': typeof AuthenticatedHackathonUsersRoute
  '/permissions': typeof AuthenticatedPermissionsRoute
  '/prizes': typeof AuthenticatedPrizesRoute
  '/roadmap-dimentorin': typeof AuthenticatedRoadmapDimentorinRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/session-dimentorin': typeof AuthenticatedSessionDimentorinRoute
  '/settings-dimentorin': typeof AuthenticatedSettingsDimentorinRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/users-dimentorin': typeof AuthenticatedUsersDimentorinRoute
  '/accounts/$id': typeof AuthenticatedAccountsIdRoute
  '/accounts/create': typeof AuthenticatedAccountsCreateRoute
  '/cms-events/$id': typeof AuthenticatedCmsEventsIdRoute
  '/cms-events/create': typeof AuthenticatedCmsEventsCreateRoute
  '/cms-testimonials/$id': typeof AuthenticatedCmsTestimonialsIdRoute
  '/cms-testimonials/create': typeof AuthenticatedCmsTestimonialsCreateRoute
  '/dashboard/$id': typeof AuthenticatedDashboardIdRoute
  '/dashboard/create': typeof AuthenticatedDashboardCreateRoute
  '/gacha-roll/$id': typeof AuthenticatedGachaRollIdRoute
  '/gacha-roll/create': typeof AuthenticatedGachaRollCreateRoute
  '/roadmap-dimentorin/$id': typeof AuthenticatedRoadmapDimentorinIdRoute
  '/roadmap-dimentorin/create': typeof AuthenticatedRoadmapDimentorinCreateRoute
  '/roles/$id': typeof AuthenticatedRolesIdRoute
  '/roles/create': typeof AuthenticatedRolesCreateRoute
  '/session-dimentorin/$id': typeof AuthenticatedSessionDimentorinIdRoute
  '/users-dimentorin/$id': typeof AuthenticatedUsersDimentorinIdRoute
  '/auth/login': typeof PublicAuthLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/cms-events': typeof AuthenticatedCmsEventsRoute
  '/cms-testimonials': typeof AuthenticatedCmsTestimonialsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dashboard-dimentorin': typeof AuthenticatedDashboardDimentorinRoute
  '/feedback-review-dimentorin': typeof AuthenticatedFeedbackReviewDimentorinRoute
  '/gacha-roll': typeof AuthenticatedGachaRollRoute
  '/hackathon-dashboard': typeof AuthenticatedHackathonDashboardRoute
  '/hackathon-submissions': typeof AuthenticatedHackathonSubmissionsRoute
  '/hackathon-teams': typeof AuthenticatedHackathonTeamsRoute
  '/hackathon-users': typeof AuthenticatedHackathonUsersRoute
  '/permissions': typeof AuthenticatedPermissionsRoute
  '/prizes': typeof AuthenticatedPrizesRoute
  '/roadmap-dimentorin': typeof AuthenticatedRoadmapDimentorinRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/session-dimentorin': typeof AuthenticatedSessionDimentorinRoute
  '/settings-dimentorin': typeof AuthenticatedSettingsDimentorinRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/users-dimentorin': typeof AuthenticatedUsersDimentorinRoute
  '/accounts/$id': typeof AuthenticatedAccountsIdRoute
  '/accounts/create': typeof AuthenticatedAccountsCreateRoute
  '/cms-events/$id': typeof AuthenticatedCmsEventsIdRoute
  '/cms-events/create': typeof AuthenticatedCmsEventsCreateRoute
  '/cms-testimonials/$id': typeof AuthenticatedCmsTestimonialsIdRoute
  '/cms-testimonials/create': typeof AuthenticatedCmsTestimonialsCreateRoute
  '/dashboard/$id': typeof AuthenticatedDashboardIdRoute
  '/dashboard/create': typeof AuthenticatedDashboardCreateRoute
  '/gacha-roll/$id': typeof AuthenticatedGachaRollIdRoute
  '/gacha-roll/create': typeof AuthenticatedGachaRollCreateRoute
  '/roadmap-dimentorin/$id': typeof AuthenticatedRoadmapDimentorinIdRoute
  '/roadmap-dimentorin/create': typeof AuthenticatedRoadmapDimentorinCreateRoute
  '/roles/$id': typeof AuthenticatedRolesIdRoute
  '/roles/create': typeof AuthenticatedRolesCreateRoute
  '/session-dimentorin/$id': typeof AuthenticatedSessionDimentorinIdRoute
  '/users-dimentorin/$id': typeof AuthenticatedUsersDimentorinIdRoute
  '/auth/login': typeof PublicAuthLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authenticated/accounts': typeof AuthenticatedAccountsRoute
  '/_authenticated/cms-events': typeof AuthenticatedCmsEventsRoute
  '/_authenticated/cms-testimonials': typeof AuthenticatedCmsTestimonialsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dashboard-dimentorin': typeof AuthenticatedDashboardDimentorinRoute
  '/_authenticated/feedback-review-dimentorin': typeof AuthenticatedFeedbackReviewDimentorinRoute
  '/_authenticated/gacha-roll': typeof AuthenticatedGachaRollRoute
  '/_authenticated/hackathon-dashboard': typeof AuthenticatedHackathonDashboardRoute
  '/_authenticated/hackathon-submissions': typeof AuthenticatedHackathonSubmissionsRoute
  '/_authenticated/hackathon-teams': typeof AuthenticatedHackathonTeamsRoute
  '/_authenticated/hackathon-users': typeof AuthenticatedHackathonUsersRoute
  '/_authenticated/permissions': typeof AuthenticatedPermissionsRoute
  '/_authenticated/prizes': typeof AuthenticatedPrizesRoute
  '/_authenticated/roadmap-dimentorin': typeof AuthenticatedRoadmapDimentorinRoute
  '/_authenticated/roles': typeof AuthenticatedRolesRoute
  '/_authenticated/session-dimentorin': typeof AuthenticatedSessionDimentorinRoute
  '/_authenticated/settings-dimentorin': typeof AuthenticatedSettingsDimentorinRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/_authenticated/users-dimentorin': typeof AuthenticatedUsersDimentorinRoute
  '/_authenticated/accounts_/$id': typeof AuthenticatedAccountsIdRoute
  '/_authenticated/accounts_/create': typeof AuthenticatedAccountsCreateRoute
  '/_authenticated/cms-events_/$id': typeof AuthenticatedCmsEventsIdRoute
  '/_authenticated/cms-events_/create': typeof AuthenticatedCmsEventsCreateRoute
  '/_authenticated/cms-testimonials_/$id': typeof AuthenticatedCmsTestimonialsIdRoute
  '/_authenticated/cms-testimonials_/create': typeof AuthenticatedCmsTestimonialsCreateRoute
  '/_authenticated/dashboard_/$id': typeof AuthenticatedDashboardIdRoute
  '/_authenticated/dashboard_/create': typeof AuthenticatedDashboardCreateRoute
  '/_authenticated/gacha-roll_/$id': typeof AuthenticatedGachaRollIdRoute
  '/_authenticated/gacha-roll_/create': typeof AuthenticatedGachaRollCreateRoute
  '/_authenticated/roadmap-dimentorin_/$id': typeof AuthenticatedRoadmapDimentorinIdRoute
  '/_authenticated/roadmap-dimentorin_/create': typeof AuthenticatedRoadmapDimentorinCreateRoute
  '/_authenticated/roles_/$id': typeof AuthenticatedRolesIdRoute
  '/_authenticated/roles_/create': typeof AuthenticatedRolesCreateRoute
  '/_authenticated/session-dimentorin_/$id': typeof AuthenticatedSessionDimentorinIdRoute
  '/_authenticated/users-dimentorin_/$id': typeof AuthenticatedUsersDimentorinIdRoute
  '/_public/auth/login': typeof PublicAuthLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/cms-events'
    | '/cms-testimonials'
    | '/dashboard'
    | '/dashboard-dimentorin'
    | '/feedback-review-dimentorin'
    | '/gacha-roll'
    | '/hackathon-dashboard'
    | '/hackathon-submissions'
    | '/hackathon-teams'
    | '/hackathon-users'
    | '/permissions'
    | '/prizes'
    | '/roadmap-dimentorin'
    | '/roles'
    | '/session-dimentorin'
    | '/settings-dimentorin'
    | '/transactions'
    | '/users-dimentorin'
    | '/accounts/$id'
    | '/accounts/create'
    | '/cms-events/$id'
    | '/cms-events/create'
    | '/cms-testimonials/$id'
    | '/cms-testimonials/create'
    | '/dashboard/$id'
    | '/dashboard/create'
    | '/gacha-roll/$id'
    | '/gacha-roll/create'
    | '/roadmap-dimentorin/$id'
    | '/roadmap-dimentorin/create'
    | '/roles/$id'
    | '/roles/create'
    | '/session-dimentorin/$id'
    | '/users-dimentorin/$id'
    | '/auth/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/cms-events'
    | '/cms-testimonials'
    | '/dashboard'
    | '/dashboard-dimentorin'
    | '/feedback-review-dimentorin'
    | '/gacha-roll'
    | '/hackathon-dashboard'
    | '/hackathon-submissions'
    | '/hackathon-teams'
    | '/hackathon-users'
    | '/permissions'
    | '/prizes'
    | '/roadmap-dimentorin'
    | '/roles'
    | '/session-dimentorin'
    | '/settings-dimentorin'
    | '/transactions'
    | '/users-dimentorin'
    | '/accounts/$id'
    | '/accounts/create'
    | '/cms-events/$id'
    | '/cms-events/create'
    | '/cms-testimonials/$id'
    | '/cms-testimonials/create'
    | '/dashboard/$id'
    | '/dashboard/create'
    | '/gacha-roll/$id'
    | '/gacha-roll/create'
    | '/roadmap-dimentorin/$id'
    | '/roadmap-dimentorin/create'
    | '/roles/$id'
    | '/roles/create'
    | '/session-dimentorin/$id'
    | '/users-dimentorin/$id'
    | '/auth/login'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/accounts'
    | '/_authenticated/cms-events'
    | '/_authenticated/cms-testimonials'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboard-dimentorin'
    | '/_authenticated/feedback-review-dimentorin'
    | '/_authenticated/gacha-roll'
    | '/_authenticated/hackathon-dashboard'
    | '/_authenticated/hackathon-submissions'
    | '/_authenticated/hackathon-teams'
    | '/_authenticated/hackathon-users'
    | '/_authenticated/permissions'
    | '/_authenticated/prizes'
    | '/_authenticated/roadmap-dimentorin'
    | '/_authenticated/roles'
    | '/_authenticated/session-dimentorin'
    | '/_authenticated/settings-dimentorin'
    | '/_authenticated/transactions'
    | '/_authenticated/users-dimentorin'
    | '/_authenticated/accounts_/$id'
    | '/_authenticated/accounts_/create'
    | '/_authenticated/cms-events_/$id'
    | '/_authenticated/cms-events_/create'
    | '/_authenticated/cms-testimonials_/$id'
    | '/_authenticated/cms-testimonials_/create'
    | '/_authenticated/dashboard_/$id'
    | '/_authenticated/dashboard_/create'
    | '/_authenticated/gacha-roll_/$id'
    | '/_authenticated/gacha-roll_/create'
    | '/_authenticated/roadmap-dimentorin_/$id'
    | '/_authenticated/roadmap-dimentorin_/create'
    | '/_authenticated/roles_/$id'
    | '/_authenticated/roles_/create'
    | '/_authenticated/session-dimentorin_/$id'
    | '/_authenticated/users-dimentorin_/$id'
    | '/_public/auth/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cms-events': {
      id: '/_authenticated/cms-events'
      path: '/cms-events'
      fullPath: '/cms-events'
      preLoaderRoute: typeof AuthenticatedCmsEventsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cms-testimonials': {
      id: '/_authenticated/cms-testimonials'
      path: '/cms-testimonials'
      fullPath: '/cms-testimonials'
      preLoaderRoute: typeof AuthenticatedCmsTestimonialsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard-dimentorin': {
      id: '/_authenticated/dashboard-dimentorin'
      path: '/dashboard-dimentorin'
      fullPath: '/dashboard-dimentorin'
      preLoaderRoute: typeof AuthenticatedDashboardDimentorinRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feedback-review-dimentorin': {
      id: '/_authenticated/feedback-review-dimentorin'
      path: '/feedback-review-dimentorin'
      fullPath: '/feedback-review-dimentorin'
      preLoaderRoute: typeof AuthenticatedFeedbackReviewDimentorinRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gacha-roll': {
      id: '/_authenticated/gacha-roll'
      path: '/gacha-roll'
      fullPath: '/gacha-roll'
      preLoaderRoute: typeof AuthenticatedGachaRollRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hackathon-dashboard': {
      id: '/_authenticated/hackathon-dashboard'
      path: '/hackathon-dashboard'
      fullPath: '/hackathon-dashboard'
      preLoaderRoute: typeof AuthenticatedHackathonDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hackathon-submissions': {
      id: '/_authenticated/hackathon-submissions'
      path: '/hackathon-submissions'
      fullPath: '/hackathon-submissions'
      preLoaderRoute: typeof AuthenticatedHackathonSubmissionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hackathon-teams': {
      id: '/_authenticated/hackathon-teams'
      path: '/hackathon-teams'
      fullPath: '/hackathon-teams'
      preLoaderRoute: typeof AuthenticatedHackathonTeamsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hackathon-users': {
      id: '/_authenticated/hackathon-users'
      path: '/hackathon-users'
      fullPath: '/hackathon-users'
      preLoaderRoute: typeof AuthenticatedHackathonUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/permissions': {
      id: '/_authenticated/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof AuthenticatedPermissionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/prizes': {
      id: '/_authenticated/prizes'
      path: '/prizes'
      fullPath: '/prizes'
      preLoaderRoute: typeof AuthenticatedPrizesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roadmap-dimentorin': {
      id: '/_authenticated/roadmap-dimentorin'
      path: '/roadmap-dimentorin'
      fullPath: '/roadmap-dimentorin'
      preLoaderRoute: typeof AuthenticatedRoadmapDimentorinRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roles': {
      id: '/_authenticated/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/session-dimentorin': {
      id: '/_authenticated/session-dimentorin'
      path: '/session-dimentorin'
      fullPath: '/session-dimentorin'
      preLoaderRoute: typeof AuthenticatedSessionDimentorinRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings-dimentorin': {
      id: '/_authenticated/settings-dimentorin'
      path: '/settings-dimentorin'
      fullPath: '/settings-dimentorin'
      preLoaderRoute: typeof AuthenticatedSettingsDimentorinRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users-dimentorin': {
      id: '/_authenticated/users-dimentorin'
      path: '/users-dimentorin'
      fullPath: '/users-dimentorin'
      preLoaderRoute: typeof AuthenticatedUsersDimentorinRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounts_/$id': {
      id: '/_authenticated/accounts_/$id'
      path: '/accounts/$id'
      fullPath: '/accounts/$id'
      preLoaderRoute: typeof AuthenticatedAccountsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounts_/create': {
      id: '/_authenticated/accounts_/create'
      path: '/accounts/create'
      fullPath: '/accounts/create'
      preLoaderRoute: typeof AuthenticatedAccountsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cms-events_/$id': {
      id: '/_authenticated/cms-events_/$id'
      path: '/cms-events/$id'
      fullPath: '/cms-events/$id'
      preLoaderRoute: typeof AuthenticatedCmsEventsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cms-events_/create': {
      id: '/_authenticated/cms-events_/create'
      path: '/cms-events/create'
      fullPath: '/cms-events/create'
      preLoaderRoute: typeof AuthenticatedCmsEventsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cms-testimonials_/$id': {
      id: '/_authenticated/cms-testimonials_/$id'
      path: '/cms-testimonials/$id'
      fullPath: '/cms-testimonials/$id'
      preLoaderRoute: typeof AuthenticatedCmsTestimonialsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cms-testimonials_/create': {
      id: '/_authenticated/cms-testimonials_/create'
      path: '/cms-testimonials/create'
      fullPath: '/cms-testimonials/create'
      preLoaderRoute: typeof AuthenticatedCmsTestimonialsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard_/$id': {
      id: '/_authenticated/dashboard_/$id'
      path: '/dashboard/$id'
      fullPath: '/dashboard/$id'
      preLoaderRoute: typeof AuthenticatedDashboardIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard_/create': {
      id: '/_authenticated/dashboard_/create'
      path: '/dashboard/create'
      fullPath: '/dashboard/create'
      preLoaderRoute: typeof AuthenticatedDashboardCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gacha-roll_/$id': {
      id: '/_authenticated/gacha-roll_/$id'
      path: '/gacha-roll/$id'
      fullPath: '/gacha-roll/$id'
      preLoaderRoute: typeof AuthenticatedGachaRollIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gacha-roll_/create': {
      id: '/_authenticated/gacha-roll_/create'
      path: '/gacha-roll/create'
      fullPath: '/gacha-roll/create'
      preLoaderRoute: typeof AuthenticatedGachaRollCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roadmap-dimentorin_/$id': {
      id: '/_authenticated/roadmap-dimentorin_/$id'
      path: '/roadmap-dimentorin/$id'
      fullPath: '/roadmap-dimentorin/$id'
      preLoaderRoute: typeof AuthenticatedRoadmapDimentorinIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roadmap-dimentorin_/create': {
      id: '/_authenticated/roadmap-dimentorin_/create'
      path: '/roadmap-dimentorin/create'
      fullPath: '/roadmap-dimentorin/create'
      preLoaderRoute: typeof AuthenticatedRoadmapDimentorinCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roles_/$id': {
      id: '/_authenticated/roles_/$id'
      path: '/roles/$id'
      fullPath: '/roles/$id'
      preLoaderRoute: typeof AuthenticatedRolesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roles_/create': {
      id: '/_authenticated/roles_/create'
      path: '/roles/create'
      fullPath: '/roles/create'
      preLoaderRoute: typeof AuthenticatedRolesCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/session-dimentorin_/$id': {
      id: '/_authenticated/session-dimentorin_/$id'
      path: '/session-dimentorin/$id'
      fullPath: '/session-dimentorin/$id'
      preLoaderRoute: typeof AuthenticatedSessionDimentorinIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users-dimentorin_/$id': {
      id: '/_authenticated/users-dimentorin_/$id'
      path: '/users-dimentorin/$id'
      fullPath: '/users-dimentorin/$id'
      preLoaderRoute: typeof AuthenticatedUsersDimentorinIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_public/auth/login': {
      id: '/_public/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof PublicAuthLoginRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRoute
  AuthenticatedCmsEventsRoute: typeof AuthenticatedCmsEventsRoute
  AuthenticatedCmsTestimonialsRoute: typeof AuthenticatedCmsTestimonialsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDashboardDimentorinRoute: typeof AuthenticatedDashboardDimentorinRoute
  AuthenticatedFeedbackReviewDimentorinRoute: typeof AuthenticatedFeedbackReviewDimentorinRoute
  AuthenticatedGachaRollRoute: typeof AuthenticatedGachaRollRoute
  AuthenticatedHackathonDashboardRoute: typeof AuthenticatedHackathonDashboardRoute
  AuthenticatedHackathonSubmissionsRoute: typeof AuthenticatedHackathonSubmissionsRoute
  AuthenticatedHackathonTeamsRoute: typeof AuthenticatedHackathonTeamsRoute
  AuthenticatedHackathonUsersRoute: typeof AuthenticatedHackathonUsersRoute
  AuthenticatedPermissionsRoute: typeof AuthenticatedPermissionsRoute
  AuthenticatedPrizesRoute: typeof AuthenticatedPrizesRoute
  AuthenticatedRoadmapDimentorinRoute: typeof AuthenticatedRoadmapDimentorinRoute
  AuthenticatedRolesRoute: typeof AuthenticatedRolesRoute
  AuthenticatedSessionDimentorinRoute: typeof AuthenticatedSessionDimentorinRoute
  AuthenticatedSettingsDimentorinRoute: typeof AuthenticatedSettingsDimentorinRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedUsersDimentorinRoute: typeof AuthenticatedUsersDimentorinRoute
  AuthenticatedAccountsIdRoute: typeof AuthenticatedAccountsIdRoute
  AuthenticatedAccountsCreateRoute: typeof AuthenticatedAccountsCreateRoute
  AuthenticatedCmsEventsIdRoute: typeof AuthenticatedCmsEventsIdRoute
  AuthenticatedCmsEventsCreateRoute: typeof AuthenticatedCmsEventsCreateRoute
  AuthenticatedCmsTestimonialsIdRoute: typeof AuthenticatedCmsTestimonialsIdRoute
  AuthenticatedCmsTestimonialsCreateRoute: typeof AuthenticatedCmsTestimonialsCreateRoute
  AuthenticatedDashboardIdRoute: typeof AuthenticatedDashboardIdRoute
  AuthenticatedDashboardCreateRoute: typeof AuthenticatedDashboardCreateRoute
  AuthenticatedGachaRollIdRoute: typeof AuthenticatedGachaRollIdRoute
  AuthenticatedGachaRollCreateRoute: typeof AuthenticatedGachaRollCreateRoute
  AuthenticatedRoadmapDimentorinIdRoute: typeof AuthenticatedRoadmapDimentorinIdRoute
  AuthenticatedRoadmapDimentorinCreateRoute: typeof AuthenticatedRoadmapDimentorinCreateRoute
  AuthenticatedRolesIdRoute: typeof AuthenticatedRolesIdRoute
  AuthenticatedRolesCreateRoute: typeof AuthenticatedRolesCreateRoute
  AuthenticatedSessionDimentorinIdRoute: typeof AuthenticatedSessionDimentorinIdRoute
  AuthenticatedUsersDimentorinIdRoute: typeof AuthenticatedUsersDimentorinIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountsRoute: AuthenticatedAccountsRoute,
  AuthenticatedCmsEventsRoute: AuthenticatedCmsEventsRoute,
  AuthenticatedCmsTestimonialsRoute: AuthenticatedCmsTestimonialsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDashboardDimentorinRoute: AuthenticatedDashboardDimentorinRoute,
  AuthenticatedFeedbackReviewDimentorinRoute:
    AuthenticatedFeedbackReviewDimentorinRoute,
  AuthenticatedGachaRollRoute: AuthenticatedGachaRollRoute,
  AuthenticatedHackathonDashboardRoute: AuthenticatedHackathonDashboardRoute,
  AuthenticatedHackathonSubmissionsRoute:
    AuthenticatedHackathonSubmissionsRoute,
  AuthenticatedHackathonTeamsRoute: AuthenticatedHackathonTeamsRoute,
  AuthenticatedHackathonUsersRoute: AuthenticatedHackathonUsersRoute,
  AuthenticatedPermissionsRoute: AuthenticatedPermissionsRoute,
  AuthenticatedPrizesRoute: AuthenticatedPrizesRoute,
  AuthenticatedRoadmapDimentorinRoute: AuthenticatedRoadmapDimentorinRoute,
  AuthenticatedRolesRoute: AuthenticatedRolesRoute,
  AuthenticatedSessionDimentorinRoute: AuthenticatedSessionDimentorinRoute,
  AuthenticatedSettingsDimentorinRoute: AuthenticatedSettingsDimentorinRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedUsersDimentorinRoute: AuthenticatedUsersDimentorinRoute,
  AuthenticatedAccountsIdRoute: AuthenticatedAccountsIdRoute,
  AuthenticatedAccountsCreateRoute: AuthenticatedAccountsCreateRoute,
  AuthenticatedCmsEventsIdRoute: AuthenticatedCmsEventsIdRoute,
  AuthenticatedCmsEventsCreateRoute: AuthenticatedCmsEventsCreateRoute,
  AuthenticatedCmsTestimonialsIdRoute: AuthenticatedCmsTestimonialsIdRoute,
  AuthenticatedCmsTestimonialsCreateRoute:
    AuthenticatedCmsTestimonialsCreateRoute,
  AuthenticatedDashboardIdRoute: AuthenticatedDashboardIdRoute,
  AuthenticatedDashboardCreateRoute: AuthenticatedDashboardCreateRoute,
  AuthenticatedGachaRollIdRoute: AuthenticatedGachaRollIdRoute,
  AuthenticatedGachaRollCreateRoute: AuthenticatedGachaRollCreateRoute,
  AuthenticatedRoadmapDimentorinIdRoute: AuthenticatedRoadmapDimentorinIdRoute,
  AuthenticatedRoadmapDimentorinCreateRoute:
    AuthenticatedRoadmapDimentorinCreateRoute,
  AuthenticatedRolesIdRoute: AuthenticatedRolesIdRoute,
  AuthenticatedRolesCreateRoute: AuthenticatedRolesCreateRoute,
  AuthenticatedSessionDimentorinIdRoute: AuthenticatedSessionDimentorinIdRoute,
  AuthenticatedUsersDimentorinIdRoute: AuthenticatedUsersDimentorinIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicAuthLoginRoute: typeof PublicAuthLoginRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAuthLoginRoute: PublicAuthLoginRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
